# Generated by Django 3.1.7 on 2021-05-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
